# Generated by Django 3.2.5 on 2021-07-23 07:16

from django.db import migrations, models
import django_extensions.db.fields
import restapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='Prod_img', max_length=250)),
                ('alt', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=restapp.models.user_directory_path)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=restapp.models.user_directory_path),
        ),
    ]
