# Generated by Django 3.2.5 on 2021-07-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20210723_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, default='Prod_img', max_length=250), max_length=250, unique_for_date='created'),
        ),
    ]
