# Generated by Django 3.2.5 on 2021-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_alter_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='title', max_length=250, unique_for_date='created'),
        ),
    ]
